# Generated by Django 5.1.3 on 2025-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='resume_file',
            new_name='uploaded_file',
        ),
    ]
