# Generated by Django 5.1.3 on 2025-02-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='resumes/')),
                ('resume_hash', models.CharField(max_length=64, unique=True)),
                ('extracted_text', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
