# Generated by Django 5.2.17 on 2026-10-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_resumeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-submitted_at'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='resumeentry',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Resume entry', 'verbose_name_plural': 'Resume entries'},
        ),
        migrations.AlterModelOptions(
            name='userresume',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Predicted resume', 'verbose_name_plural': 'Predicted resumes'},
        ),
        migrations.AlterField(
            model_name='company',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumeentry',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resumeentry',
            name='resume_hash',
            field=models.CharField(help_text='SHA-256 hash to prevent duplicates', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='prediction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='userresume',
            index=models.Index(fields=['-uploaded_at'], name='home_userre_uploade_caecdf_idx'),
        ),
    ]
